// Chat-redesign (chat-B2 signed contract) — per-turn 2–3 sentence summaries.
//
// The Turn Card's summary is generated by a short, cached, headless `claude -p`
// pass that MUST use Haiku (the small/fast/cheap tier). It is:
//   • content-addressed + cached on disk → computed ONCE per turn, ever;
//   • NON-BLOCKING → the request returns whatever's cached NOW and kicks off
//     background generation for the most-recent uncached turns; the client
//     refetches to pick newly-generated ones up. While a turn's summary isn't
//     ready, the client falls back to the first few sentences.
//
// The step list comes from the recorded tool calls (groupTurns) — no model.
// `generate` is injectable so tests never spawn a real claude.

import { spawn } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import os from "node:os";

import type { TranscriptMessage } from "../../shared/api-types";
import { groupTurns, type TurnItem } from "../../shared/groupTurns";

export type SummariseFn = (said: string) => Promise<string>;

const CACHE_DIR = join(os.homedir(), ".sulis", "cockpit-cache", "summaries");
const MAX_CONCURRENT = 3;
const ENQUEUE_CAP = 8; // most-recent uncached turns to queue per request
// `claude -p` has a heavy cold start in this environment (~30–60s — global
// config + model init), so give it real headroom. Generation is background +
// cached-once, so the latency is paid once per turn and never again. (A future
// optimisation is to call the Haiku API directly instead of spawning the CLI,
// which would cut this to ~1–2s — see the follow-up task.)
const GEN_TIMEOUT_MS = 90_000;

function hashSaid(said: string): string {
  return createHash("sha256").update(said).digest("hex");
}
function cachePath(hash: string): string {
  return join(CACHE_DIR, `${hash}.txt`);
}

const prompt = (said: string): string =>
  `Summarise what the assistant did in this turn for a NON-TECHNICAL founder, in 2–3 short sentences. The FIRST sentence is the headline outcome — what happened, plain and concrete. The next one or two sentences add the why or the result. No preamble, no markdown headings, no IDs or file paths unless essential. Return ONLY the summary.\n\nTurn:\n"""\n${said.slice(0, 6000)}\n"""`;

/** Default generator: a headless Haiku call. Resolves "" on any failure
 *  (timeout / spawn error / non-zero) so the caller falls back gracefully. */
export const haikuSummarise: SummariseFn = (said) =>
  new Promise((resolve) => {
    let out = "";
    let done = false;
    const finish = (v: string) => {
      if (!done) {
        done = true;
        resolve(v);
      }
    };
    let child: ReturnType<typeof spawn>;
    try {
      child = spawn(
        "claude",
        ["-p", prompt(said), "--model", "haiku", "--strict-mcp-config"],
        {
        stdio: ["ignore", "pipe", "ignore"],
        // CRITICAL: run from a NEUTRAL dir. From the repo, `claude -p` loads
        // the whole project (CLAUDE.md, MCP servers, agents) and takes ~60s to
        // start — well past our timeout, so every summary came back empty.
        // Summarisation needs no project context, so a temp cwd makes it the
        // fast ~2–5s call it should be. (chat-B2 fix.)
        cwd: os.tmpdir(),
      });
    } catch {
      finish("");
      return;
    }
    const timer = setTimeout(() => {
      try {
        child.kill("SIGKILL");
      } catch {
        /* already gone */
      }
      finish("");
    }, GEN_TIMEOUT_MS);
    child.stdout?.on("data", (d: Buffer) => {
      out += d.toString();
    });
    child.on("error", () => {
      clearTimeout(timer);
      finish("");
    });
    child.on("close", () => {
      clearTimeout(timer);
      finish(out.trim());
    });
  });

// In-memory cache + background queue (single-process local app).
const mem = new Map<string, string>();
const inFlight = new Set<string>();
let active = 0;
const queue: Array<{ hash: string; said: string; gen: SummariseFn }> = [];

async function readCache(hash: string): Promise<string | null> {
  const m = mem.get(hash);
  if (m) return m;
  try {
    const s = (await readFile(cachePath(hash), "utf8")).trim();
    if (s) {
      mem.set(hash, s);
      return s;
    }
  } catch {
    /* miss */
  }
  return null;
}

async function writeCache(hash: string, summary: string): Promise<void> {
  mem.set(hash, summary);
  try {
    await mkdir(CACHE_DIR, { recursive: true });
    await writeFile(cachePath(hash), summary, "utf8");
  } catch {
    /* best-effort; the in-memory copy still serves this process */
  }
}

function pump(): void {
  while (active < MAX_CONCURRENT && queue.length > 0) {
    const job = queue.shift()!;
    active += 1;
    job
      .gen(job.said)
      .then((summary) => (summary ? writeCache(job.hash, summary) : undefined))
      .catch(() => {})
      .finally(() => {
        active -= 1;
        inFlight.delete(job.hash);
        pump();
      });
  }
}

export interface TurnSummariesOpts {
  /** Injectable generator; defaults to the real Haiku call. */
  generate?: SummariseFn;
  /** How many most-recent uncached turns to queue this request. */
  enqueueCap?: number;
}

/**
 * The summaries available NOW (`{ turnKey -> summary }`), plus a kicked-off
 * background generation pass for the most-recent uncached turns. Never awaits
 * generation — returns immediately so the request stays fast.
 */
export async function getTurnSummaries(
  messages: TranscriptMessage[],
  opts: TurnSummariesOpts = {},
): Promise<Record<string, string>> {
  const gen = opts.generate ?? haikuSummarise;
  const cap = opts.enqueueCap ?? ENQUEUE_CAP;

  const turns = groupTurns(messages).filter(
    (i): i is TurnItem => i.type === "turn" && i.said.trim().length > 0,
  );

  const result: Record<string, string> = {};
  const uncached: Array<{ hash: string; said: string }> = [];

  for (const t of turns) {
    const hash = hashSaid(t.said);
    const cached = await readCache(hash);
    if (cached) result[t.key] = cached;
    else uncached.push({ hash, said: t.said });
  }

  // Queue the most-recent uncached turns (end of the list = newest first seen).
  for (const u of uncached.slice(-cap)) {
    if (inFlight.has(u.hash)) continue;
    inFlight.add(u.hash);
    queue.push({ hash: u.hash, said: u.said, gen });
  }
  pump();

  return result;
}
